language: c
matrix:
  include:
    - os: windows
      install: choco install mingw --version 4.9.3 --force
      script: mingw32-make release_windows
    - os: linux
      script: make release
      compile:
      - gcc
      - clang
    - os: osx
      compile:
      - gcc
      - clang
      script: make release
