language: c
matrix:
  include:
    - os: windows
      install: choco install mingw
      script: cmake release_windows
    - os: linux
      script: make release
      compile:
      - gcc
      - clang
    - os: osx
      compile:
      - gcc
      - clang
      script: make release