language: c
matrix:
  include:
    - os: windows
      install: choco install mingw
      script: cmake release_windows
    - os: linux
      script: make release
    - os: osx
      script: make release
os:
  - windows
  - linux
  - osx
compile:
  - gcc
  - clang
before_install:
  - mkdir bin
script:
  - cmake